### ISSUE TITLE
Make the website look cool

### ISSUE THREAD

**Issue by hiruthicShaSS** [hiruthic2002/pLANTEr#3]
Use your JS and CSS skills to make a perfect website for pLANTEr
- Any JS is allowed
- Any type of CSS allowed
#### Website folder conatins the website. If you can work with NodeJS please feel free to work with that too.

I just need your help🥰

**Comment by aaronzshey** [comment]
We could link this with the animations issue.

**Comment by hiruthicShaSS** [comment]
This is a duplicate issue of #1
